version: 2

updates:

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: 'feat:'
    ignore:
      - dependency-name: 'alpine'
        versions:
          - '3.15'

  - package-ecosystem: 'github-actions'
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: 'chore:'
