name: 'Docker Publish'

on:
  repository_dispatch:

permissions:
  packages: write

jobs:
  publish-stable:
    name: Docker Publish

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          ref: refs/tags/${{ github.event.client_payload.tag }}
      -
        name: Prepare
        run: |
          TAG=${{ github.event.client_payload.tag }}
          echo "TAG=${TAG#v}" >> $GITHUB_ENV
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: '.'
          file: './Dockerfile'
          platforms: 'linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7'
          push: true
          tags: |
            ghcr.io/ttionya/vaultwarden-backup:latest
            ghcr.io/ttionya/vaultwarden-backup:${{ env.TAG }}
